name: Python application test

on:
  pull_request:
    branches: [ main ] # or any other branch you want to run tests against
  workflow_dispatch:  # This line allows manual triggering of the workflow from GitHub's UI


jobs:
  build:
    name: python test

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9' # Specify the Python version you need

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Install the project in editable mode
      run: pip install -e .

    - name: Run tests
      run: pytest
